openapi: 3.0.0
info:
  title: MiEcommerce
  version: 1.0.0
  description: |-
    Esta es la API de MiEcommerce.
    
    Links:
    - [Repositorio de Github](https://github.com/MRNCallero/MiEcomerce8)
  
servers:
  - url: http://localhost:8080/api/v1
    description: Entorno Desarrollo
    
tags:
  - name: usuarios
    description: Todos los endpoints de usuarios
  - name: productos
    description: Todos los endpoints de productos
  - name: pictures
    description: Todos los endpoints de imagenes

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT​

paths:
  /users:
    get:
      tags: 
        - usuarios
      summary: Retorna listado de usuario.
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: Un array de usuarios
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
        '500':    # status code
          description: Server Error
          content:
            application/json:
              schema: 
                type: object
                properties:
                  ok:
                    type: boolean
                  message:
                    type: string
    post:
      tags: 
        - usuarios
      summary: Crear un usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - username
                - password
                - firstname
                - lastname
              properties:
                email:
                  type: string
                username:
                  type: string
                password:
                  type: string
                firstname:
                  type: string
                lastname:
                  type: string
                profilepic:
                  type: string
      responses: 
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  email:
                    type: string
                  username:
                    type: string
                  password:
                    type: string
                  firstname:
                    type: string
                  lastname:
                    type: string
                  profilepic:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  message:
                    type: string
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  message:
                    type: string
  /users/{id}:
    get:
      tags:
        - usuarios
      summary: Lista el usuario con el id recibido
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Id del usuario
      responses: 
        '200':
          description: El usuario ha sido eliminado
          content:
            application/json:
              schema: 
                type: object
        '409':
          description: El usuario no ha sido eliminado

    delete:
      tags: 
        - usuarios
      summary: Elimina un usuario
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: Nombre de usuario
      
      responses: 
        '200':
          description: El usuario ha sido eliminado
        '409':
          description: El usuario no ha sido eliminado



  /demo:
    get:
      tags: 
        - usuarios
      summary: Retorna listado de usuario.
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: Un array de usuarios
        '401':    # status code
          description: Usuario no autorizado  
          
  /login:
    post:
      tags: 
        - usuarios
      summary: Retorna un token para utilizar en el endpoint demo
      responses:
        '200':    # status code
          description: Token válido
        '401':    # status code
          description: Usuario no autorizado